### ISSUE TITLE
Support for OTP 22+

### ISSUE THREAD

**Issue by ConnorRigby** [rusterlium/rustler#331]
I'm sure this has been discussed, but following the docs verbatim will error on otp 22 or 23 due to a dep of a dep of a dep of a dep

**Comment by filmor** [comment]
Both OTP22 and 23 are supported on master and in the 0.22 RC, can you please provide the precise error you are getting?

**Comment by ConnorRigby** [comment]
Just following the readme instructions this is what i get.
Last week when i tried to get started, i got an error that said something like `otp 23 is not supported` when compiling some sub dependency. I'm sure this is just a documentation issue, but i have no idea where to look. 

```
error: cannot find macro `rustler_atoms` in this scope
 --> src/lib.rs:4:5
  |
4 |     rustler_atoms! {
  |     ^^^^^^^^^^^^^

error[E0425]: cannot find function `ok` in module `atoms`
  --> src/lib.rs:24:16
   |
24 |     Ok((atoms::ok(), num1 + num2).encode(env))
   |                ^^ not found in `atoms`
   |
help: consider importing this function
   |
1  | use rustler::types::atom::ok;
   |

warning: unused import: `Encoder`
 --> src/lib.rs:1:15
  |
1 | use rustler::{Encoder, Env, Error, Term};
  |               ^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to 2 previous errors; 1 warning emitted

For more information about this error, try `rustc --explain E0425`.
error: could not compile `rustlerbug_nif`.

To learn more, run the command again with --verbose.
** (RuntimeError) Rust NIF compile error (rustc exit code 101)
    lib/mix/tasks/compile.rustler.ex:68: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir 1.10.3) lib/enum.ex:1396: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:15: Mix.Tasks.Compile.Rustler.run/1
    (mix 1.10.3) lib/mix/task.ex:330: Mix.Task.run_task/3
    (mix 1.10.3) lib/mix/tasks/compile.all.ex:76: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.10.3) lib/mix/tasks/compile.all.ex:56: Mix.Tasks.Compile.All.do_compile/4
    (mix 1.10.3) lib/mix/tasks/compile.all.ex:27: anonymous fn/2 in Mix.Tasks.Compile.All.run/1
    (mix 1.10.3) lib/mix/tasks/compile.all.ex:43: Mix.Tasks.Compile.All.with_logger_app/2
```

**Comment by praveenperera** [comment]
Did you pull `rustler_atoms` into scope? If not try `rustler::rustler_atoms!`

```
rustler::rustler_atoms!{
...
}
``

https://github.com/rusterlium/rustler/issues/260

**Comment by ConnorRigby** [comment]
This seems like a thing that should be in the default project? Anyway that fixed it thanks
