### ISSUE TITLE
Rust.compiler.config.metada! failing to get metadata

### ISSUE THREAD

**Issue by henriquesati** [rusterlium/rustler#674]
I'm trying to build rust nifs but i'm getting

```
(RuntimeError) calling cargo metadata failed.

    (rustler 0.35.1) lib/rustler/compiler/config.ex:81: Rustler.Compiler.Config.metadata!/1
    (rustler 0.35.1) lib/rustler/compiler/config.ex:63: Rustler.Compiler.Config.build/1
    (rustler 0.35.1) lib/rustler/compiler.ex:8: Rustler.Compiler.compile_crate/3
    
```
    i'm getting this error both on Ubuntu 22.02 Jammy (docker) and Windows.
    At first I thought It was a cross-compilation issue (i'm building inside a container but windows dependencies keep being loaded, so I deleted _builds directory from being pushed and the native/elixir_solana that contained target and cargo lock to avoid pushing extra files to the container (to rebuild rustler as vanilla)
 dockerfile
    
```
FROM ubuntu:22.04


ENV LANG=C.UTF-8
ENV HOME=/root

RUN set -xe \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        wget \
        gnupg2 \
        build-essential \
        libncurses5-dev \
        libssl-dev \
        fop \
        xsltproc \
        ca-certificates \
        libssl-dev \
        pkg-config \
        git \
        unzip \
        make \
        bash \
        libreadline-dev \
        zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN set -xe \
    && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y \
    && . "$HOME/.cargo/env" \
    && rustup install stable \
    && rustup default stable

# Instala Erlang via repositório oficial
RUN set -xe \
    && echo "deb http://binaries2.erlang-solutions.com/ubuntu/ jammy-esl-erlang-26 contrib" >> /etc/apt/sources.list \
    && wget -q https://binaries2.erlang-solutions.com/GPG-KEY-pmanager.asc -O - | apt-key add - \
    && apt-get update \
    && apt-get install -y --no-install-recommends esl-erlang \
    && rm -rf /var/lib/apt/lists/*

RUN set -xe \
    && git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.10.0 \
    && echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bashrc \
    && echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc


RUN set -xe \
    && ~/.asdf/bin/asdf plugin add elixir \
    && ~/.asdf/bin/asdf install elixir 1.17.0\
    && ~/.asdf/bin/asdf global elixir 1.17.0\
    && ~/.asdf/bin/asdf reshim elixir

WORKDIR /app
COPY . .


CMD ["/bin/bash"]

```

cargo.toml (container file)

`  GNU nano 6.2                                           Cargo.toml                                                     [package]
name = "elixir_solana"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "elixir_solana"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
bip39 = "2.0.0"
bs58 = "0.5.1"
solana-sdk = "2.0.5"
solana-client = "2.0.5"

`
src file
`
use solana_sdk::signature::{Keypair, Signer};
use solana_sdk::pubkey::Pubkey;
use solana_client::rpc_client::RpcClient;
use bs58;
use rustler::{NifResult, Error};
use rustler::types::Atom;

rustler::atoms! {
    ok,      // Equivalente ao :ok no Elixir
    error    // Equivalente ao :error no Elixir
}
enum DataType {
    String(String),
    Number(i32),
  }
#[rustler::nif]
fn add(a: i64, b: i64) -> i64 {
    a + b
}

#[rustler::nif]
fn sol_get_pub_private<'a>() ->   NifResult<(Atom, String)> {
    let keypair = Keypair::new();
    let public_key = keypair.pubkey();
    let secret_key = keypair.secret().to_bytes();

    let mut  combined_to_walletuse = secret_key.to_vec();
    combined_to_walletuse.extend_from_slice(&public_key.to_bytes());

    let private = bs58::encode(&combined_to_walletuse).into_string();
    let private_verify = DataType::String(private);
    match private_verify {
        
        DataType::String(priv_key) => {
            let result = format!(
                "{}-{}",
                public_key,
                priv_key
            );
            return Ok((ok(), result));
        },
        DataType::Number(_) => {
            return Ok((error(), String::from("FAILED GETTING KEYS")));

        } 
      }
}

#[rustler::nif(schedule = "DirtyIo")]
fn sol_check_balance(adress: String) -> u64 {
    use std::str::FromStr;
    let provider: String = "https://misty-rough-dream.solana-devnet.quiknode.pro/0ba170ad5874683fea1731482d0ae50b42262307/".to_string();

    let connection = RpcClient::new(provider); 
    let pubkey = Pubkey::from_str(&adress).unwrap();
    let balance = connection.get_balance(&pubkey).unwrap();
    return balance/1000000000

}

rustler::init!("Elixir.Solana");
`
I modified my windows build to use features flag, and now the output is 
`    erlang.erl:4716: :erlang.open_port({:spawn_executable, ~c"c:/Users/henri/.cargo/bin/cargo.exe"}, [:use_stdio, {:cd, "native/solana_elixir"}, :exit_status, :binary, :hide, {:args, ["metadata", "--format-version=1"]}])
    (elixir 1.17.3) lib/system.ex:1131: System.do_cmd/3
    (rustler 0.35.1) lib/rustler/compiler/config.ex:76: Rustler.Compiler.Config.metadata!/1
    (rustler 0.35.1) lib/rustler/compiler/config.ex:63: Rustler.Compiler.Config.build/1
    (rustler 0.35.1) lib/rustler/compiler.ex:8: Rustler.Compiler.compile_crate/3
    lib/testespay/nifs/solana.ex:2: (module)`
`[package]
name = "elixir_solana"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "elixir_solana"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = { version = "0.34.0", features = ["nif_version_2_17"]}
bip39 = "2.0.0"
bs58 = "0.5.1"
solana-sdk = "2.0.5"
solana-client = "2.0.5"`

**Comment by henriquesati** [comment]
solved by installing **rustler = "0.35.1"**
